# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1000, 700))
        self.label.setStyleSheet("border-image: url(:/wallpaper/pexels-pixabay-36717.jpg);\n"
"border-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 180, 40, 30))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255,0%);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/pin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(40, 30))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 310, 381, 141))
        self.label_3.setStyleSheet("font: 87 26pt \"Arial Black\";\n"
"color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 0,30%);\n"
"border-radius:30px;")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 490, 210, 120))
        self.label_5.setStyleSheet("font: 87 26pt \"Arial Black\";\n"
"color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 0,30%);\n"
"border-radius:20px;")
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(300, 490, 210, 120))
        self.label_6.setStyleSheet("font: 87 26pt \"Arial Black\";\n"
"color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 0,30%);\n"
"border-radius:20px;")
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(530, 490, 210, 120))
        self.label_7.setStyleSheet("font: 87 26pt \"Arial Black\";\n"
"color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 0,30%);\n"
"border-radius:20px;")
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(760, 490, 210, 120))
        self.label_8.setStyleSheet("font: 87 26pt \"Arial Black\";\n"
"color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 0,30%);\n"
"border-radius:20px;")
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(780, 330, 210, 120))
        self.label_9.setStyleSheet("font: 87 26pt \"Arial Black\";\n"
"color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 0,30%);\n"
"border-radius:20px;")
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(780, 170, 210, 120))
        self.label_10.setStyleSheet("font: 87 26pt \"Arial Black\";\n"
"color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 0,30%);\n"
"border-radius:20px;")
        self.label_10.setText("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(70, 330, 210, 120))
        self.label_11.setStyleSheet("font: 87 26pt \"Arial Black\";\n"
"color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 0,30%);\n"
"border-radius:20px;")
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 330, 331, 61))
        self.label_4.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
"color: rgb(0, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.Date_edit = QtWidgets.QLabel(self.centralwidget)
        self.Date_edit.setGeometry(QtCore.QRect(500, 390, 131, 31))
        self.Date_edit.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: rgb(170, 255, 255);")
        self.Date_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.Date_edit.setObjectName("Date_edit")
        self.day_edit = QtWidgets.QLabel(self.centralwidget)
        self.day_edit.setGeometry(QtCore.QRect(400, 390, 101, 31))
        self.day_edit.setStyleSheet("font: 75 12pt \"8514oem\";\n"
"color: rgb(85, 255, 255);")
        self.day_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.day_edit.setObjectName("day_edit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 340, 161, 30))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(40, 205, 253);\n"
"font: 75 8pt \"8514oem\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/low-temperature.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.Temperature_edit = QtWidgets.QLabel(self.centralwidget)
        self.Temperature_edit.setGeometry(QtCore.QRect(120, 380, 91, 71))
        self.Temperature_edit.setStyleSheet("font: 87 26pt \"Arial Black\";\n"
"color: rgb(0, 208, 255);")
        self.Temperature_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.Temperature_edit.setObjectName("Temperature_edit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 380, 40, 30))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255,0%);")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/celsius.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 498, 160, 40))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(40, 205, 253);\n"
"font: 75 8pt \"8514oem\";")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/sunrise.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.Sunrise_edit = QtWidgets.QLabel(self.centralwidget)
        self.Sunrise_edit.setGeometry(QtCore.QRect(70, 540, 211, 51))
        self.Sunrise_edit.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
"color: rgb(0, 255, 255);")
        self.Sunrise_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.Sunrise_edit.setObjectName("Sunrise_edit")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 498, 161, 40))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(40, 205, 253);\n"
"font: 75 8pt \"8514oem\";")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/sunset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.Sunset_edit = QtWidgets.QLabel(self.centralwidget)
        self.Sunset_edit.setGeometry(QtCore.QRect(300, 540, 211, 51))
        self.Sunset_edit.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
"color: rgb(0, 255, 255);")
        self.Sunset_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.Sunset_edit.setObjectName("Sunset_edit")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(550, 500, 161, 30))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(40, 205, 253);\n"
"font: 75 8pt \"8514oem\";")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.Visibility_edit = QtWidgets.QLabel(self.centralwidget)
        self.Visibility_edit.setGeometry(QtCore.QRect(570, 550, 111, 41))
        self.Visibility_edit.setStyleSheet("font: 87 26pt \"Arial Black\";\n"
"color: rgb(0, 208, 255);")
        self.Visibility_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.Visibility_edit.setObjectName("Visibility_edit")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(680, 570, 31, 21))
        self.label_19.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 255, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(770, 500, 181, 30))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(40, 205, 253);\n"
"font: 75 8pt \"8514oem\";")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/resilience.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.Air_pressure_edit = QtWidgets.QLabel(self.centralwidget)
        self.Air_pressure_edit.setGeometry(QtCore.QRect(800, 550, 111, 41))
        self.Air_pressure_edit.setStyleSheet("font: 87 24pt \"Arial Black\";\n"
"color: rgb(0, 208, 255);")
        self.Air_pressure_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Air_pressure_edit.setObjectName("Air_pressure_edit")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(920, 570, 41, 21))
        self.label_21.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 255, 255);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(800, 340, 161, 30))
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(40, 205, 253);\n"
"font: 75 8pt \"8514oem\";")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/wind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon7)
        self.pushButton_8.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.Wind_edit = QtWidgets.QLabel(self.centralwidget)
        self.Wind_edit.setGeometry(QtCore.QRect(810, 380, 101, 41))
        self.Wind_edit.setStyleSheet("font: 87 24pt \"Arial Black\";\n"
"color: rgb(0, 208, 255);")
        self.Wind_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Wind_edit.setObjectName("Wind_edit")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(920, 400, 41, 21))
        self.label_23.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 255, 255);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(800, 180, 171, 30))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(40, 205, 253);\n"
"font: 75 8pt \"8514oem\";")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/humidity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon8)
        self.pushButton_9.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(890, 250, 21, 21))
        self.label_24.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 255, 255);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.Humidity_edit = QtWidgets.QLabel(self.centralwidget)
        self.Humidity_edit.setGeometry(QtCore.QRect(830, 230, 61, 41))
        self.Humidity_edit.setStyleSheet("font: 87 24pt \"Arial Black\";\n"
"color: rgb(0, 208, 255);")
        self.Humidity_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Humidity_edit.setObjectName("Humidity_edit")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(80, 170, 230, 120))
        self.label_26.setStyleSheet("font: 87 26pt \"Arial Black\";\n"
"color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 0,30%);\n"
"border-radius:20px;")
        self.label_26.setText("")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.Weather_change_icon = QtWidgets.QPushButton(self.centralwidget)
        self.Weather_change_icon.setGeometry(QtCore.QRect(100, 230, 40, 30))
        self.Weather_change_icon.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(40, 205, 253);\n"
"font: 75 8pt \"8514oem\";")
        self.Weather_change_icon.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Clear Sky.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Weather_change_icon.setIcon(icon9)
        self.Weather_change_icon.setIconSize(QtCore.QSize(40, 30))
        self.Weather_change_icon.setObjectName("Weather_change_icon")
        self.weather_info = QtWidgets.QLabel(self.centralwidget)
        self.weather_info.setGeometry(QtCore.QRect(150, 230, 160, 30))
        self.weather_info.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 75 8pt \"8514oem\";")
        self.weather_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weather_info.setObjectName("weather_info")
        self.Refresh_button = QtWidgets.QPushButton(self.centralwidget)
        self.Refresh_button.setGeometry(QtCore.QRect(40, 40, 131, 30))
        self.Refresh_button.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(40, 205, 253);\n"
"font: 75 8pt \"8514oem\";")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Refresh_button.setIcon(icon10)
        self.Refresh_button.setIconSize(QtCore.QSize(40, 30))
        self.Refresh_button.setObjectName("Refresh_button")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(850, 660, 131, 30))
        self.label_28.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 75 8pt \"8514oem\";")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.Exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.Exit_button.setGeometry(QtCore.QRect(950, 20, 40, 30))
        self.Exit_button.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(40, 205, 253);\n"
"font: 75 8pt \"8514oem\";")
        self.Exit_button.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit_button.setIcon(icon11)
        self.Exit_button.setIconSize(QtCore.QSize(40, 30))
        self.Exit_button.setObjectName("Exit_button")
        self.Minimize_button = QtWidgets.QPushButton(self.centralwidget)
        self.Minimize_button.setGeometry(QtCore.QRect(900, 20, 40, 30))
        self.Minimize_button.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(40, 205, 253);\n"
"font: 75 8pt \"8514oem\";")
        self.Minimize_button.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Minimize_button.setIcon(icon12)
        self.Minimize_button.setIconSize(QtCore.QSize(40, 30))
        self.Minimize_button.setObjectName("Minimize_button")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(390, 30, 241, 30))
        self.pushButton_14.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(40, 205, 253);\n"
"font: 75 8pt \"8514oem\";")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/cloudy-day.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon13)
        self.pushButton_14.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_14.setObjectName("pushButton_14")
        self.City_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.City_edit.setGeometry(QtCore.QRect(140, 180, 151, 30))
        self.City_edit.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(0, 255, 255);\n"
"font: 75 8pt \"8514oem\";\n"
"border:0px;")
        self.City_edit.setObjectName("City_edit")
        self.Display_error_message = QtWidgets.QLabel(self.centralwidget)
        self.Display_error_message.setGeometry(QtCore.QRect(300, 635, 441, 31))
        self.Display_error_message.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 14pt \"Arial\";")
        self.Display_error_message.setText("")
        self.Display_error_message.setAlignment(QtCore.Qt.AlignCenter)
        self.Display_error_message.setObjectName("Display_error_message")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "00:00"))
        self.Date_edit.setText(_translate("MainWindow", "00-00-00"))
        self.day_edit.setText(_translate("MainWindow", "N/a"))
        self.pushButton_2.setText(_translate("MainWindow", "Temperature"))
        self.Temperature_edit.setText(_translate("MainWindow", "N/a"))
        self.pushButton_4.setText(_translate("MainWindow", " Sunrise"))
        self.Sunrise_edit.setText(_translate("MainWindow", "00:00"))
        self.pushButton_5.setText(_translate("MainWindow", "Sunset"))
        self.Sunset_edit.setText(_translate("MainWindow", "00:00"))
        self.pushButton_6.setText(_translate("MainWindow", "Visibility"))
        self.Visibility_edit.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "mi"))
        self.pushButton_7.setText(_translate("MainWindow", " Air Pressure"))
        self.Air_pressure_edit.setText(_translate("MainWindow", "N/a"))
        self.label_21.setText(_translate("MainWindow", "hpa"))
        self.pushButton_8.setText(_translate("MainWindow", " WNW Wind"))
        self.Wind_edit.setText(_translate("MainWindow", "N/a"))
        self.label_23.setText(_translate("MainWindow", "m/s"))
        self.pushButton_9.setText(_translate("MainWindow", " Humidity"))
        self.label_24.setText(_translate("MainWindow", "%"))
        self.Humidity_edit.setText(_translate("MainWindow", "0"))
        self.weather_info.setText(_translate("MainWindow", "------------"))
        self.Refresh_button.setText(_translate("MainWindow", " Refresh"))
        self.label_28.setText(_translate("MainWindow", "Version 1.0"))
        self.pushButton_14.setText(_translate("MainWindow", " Weather Forecast"))
        self.City_edit.setPlaceholderText(_translate("MainWindow", "Enter City"))
